@startuml

InputHandler -> Game : getMoveLeft(), getMoveRight(), getAndResetJump()
Game -> Map : handleInput(moveRight)
Game -> Player : handleInput(moveLeft, moveRight, jump)

loop per frame update
    Game -> Map : update()
    Game -> Player : update(platforms, foods, enemies, traps, cave)

    alt Collides with obstacle
        Player -> Health : decreaseHP()
    end

    alt Collides with food
        Player -> Food : checkCollision()
        Food -> Health : increaseHP()
    end

    Player -> Health : decreaseHPOverTime()

    Game -> Health : getHealth()
    alt health <= 0
        Game -> GameState : set to "gameOver"
    end

    Player -> Cave : checkArrival()
    alt reached
        Game -> GameState : set to "levelComplete"
    end
end

@enduml
